# Generated by Django 5.2 on 2025-05-14 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_city_user_cities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cities',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.city'),
        ),
    ]
